language: android

jdk: oraclejdk7

env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-18  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-17  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-16  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-15  ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-13  ANDROID_ABI=armeabi
    - ANDROID_TARGET=android-10  ANDROID_ABI=armeabi
    - ANDROID_TARGET=android-8   ANDROID_ABI=armeabi

android:
  components:
    - build-tools-19.0.3
    - android-19
    - sysimg-19
    - android-18
    - sysimg-18
    - android-17
    - sysimg-17
    - android-16
    - sysimg-16
    - android-15
    - sysimg-15
    - android-13
    - android-10
    - sysimg-10
    - android-8
  licenses:
    - android-sdk-license-bcbbd656

before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - chmod +x ./wait_for_emulator
  - adb logcat | tee logcat.txt &
  - ./wait_for_emulator
  - adb shell input keyevent 82 &

script: ant -buildfile ./test/build.xml clean emma debug install test

after_script:
  - pkill -KILL -f tee
  - pkill -KILL -f adb
